name: Deploy to S3

on:
  push:
    branches: [main]

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get latest Hugo version
        run: |
          LATEST_HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${LATEST_HUGO_VERSION}/hugo_extended_${LATEST_HUGO_VERSION:1}_Linux-64bit.tar.gz | tar -xvzf-
      - name: Move Hugo executable file
        run: |
          sudo mv hugo /usr/local/bin/
          hugo version
      - name: Build the Site
        run: hugo
      - name: Deploy to S3 and Invalidate Cache
        uses: Reggionick/s3-deploy@v4.0.0
        with:
          folder: ./public
          bucket: ${{ secrets.AWS_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: ".*/*,*/*,**"
      # - name: Sync with AWS S3 bucket & invalidate Cloudfront cache
      #   run: |
      #     aws s3 sync ./public s3://${{ secrets.AWS_BUCKET }} --acl public-read
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths '/*'
